### ISSUE TITLE
regex escape sequences are not invalid

### ISSUE THREAD

**Issue by rbuckland** [hgrecco/stringparser#2]
Python 3.9 and made invalid escape sequences invalid for 3.9+

```
\. changes to \\. etc
```
This will need to be resolved for python 3.9+ environments.
 
![image](https://user-images.githubusercontent.com/1148383/197916056-a9a7709a-c764-4c1a-972b-5fe03f9847c4.png)

**Comment by hgrecco** [comment]
Thanks!

**Comment by rbuckland** [comment]
Thanks for the fast turn around ! :-)

**Comment by hgrecco** [comment]
Thank you. I think I have not made any real change in this project in about 10 years! I was working fine for a loooong time.
